// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

import { c } from 'hyperschema/runtime'

const VERSION = 1

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @hypernotes/hello-request
const encoding0 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.world) c.string.preencode(state, m.world)
  },
  encode(state, m) {
    const flags = m.world ? 1 : 0

    c.uint.encode(state, flags)

    if (m.world) c.string.encode(state, m.world)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      world: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @hypernotes/hello-response
const encoding1 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.message) c.string.preencode(state, m.message)
  },
  encode(state, m) {
    const flags = m.message ? 1 : 0

    c.uint.encode(state, flags)

    if (m.message) c.string.encode(state, m.message)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      message: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@hypernotes/hello-request':
      return encoding0
    case '@hypernotes/hello-response':
      return encoding1
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

export { resolveStruct, getStruct, getEnum, getEncoding, encode, decode, setVersion, version }
